name: Lint-Build-Test-Publish

on:
  push:
    branches:
      - main
jobs:
  pre-release-checks:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install
      - name: Lint
        run: yarn lint
      # - name: Build & Test
      #   run: yarn test

  publish-npm-package:
    needs: [pre-release-checks]
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn install
      - name: Build
        run: yarn build
        env:
          GIT_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Publish to NPM Package Repo
        env:
          GIT_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        run: yarn run semantic-release
